/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Awal;
import javax.swing.JOptionPane;
import java.sql.*;
import pro.DatabaseConnection;

/**
 *
 * @author LENOVO
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Passreg = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        log = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nama_kasir = new javax.swing.JTextField();
        alamatreg = new javax.swing.JTextField();
        umur = new javax.swing.JTextField();
        Usnreg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PeremCheckBox = new javax.swing.JCheckBox();
        LakiCheckBox = new javax.swing.JCheckBox();
        regbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regis.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 450, 680));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -60, -1, 206));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 82, 48));
        jLabel3.setText("REGISTER");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, 90));
        jPanel2.add(Passreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 340, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nama");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        log.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        log.setForeground(new java.awt.Color(255, 0, 51));
        log.setText("Login");
        log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logMouseClicked(evt);
            }
        });
        jPanel2.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 610, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Belum Punya Akun?");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 610, -1, -1));
        jPanel2.add(nama_kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 340, 50));
        jPanel2.add(alamatreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 340, 50));
        jPanel2.add(umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 340, 50));
        jPanel2.add(Usnreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 340, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("User Name");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Umur");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Jenis Kelamin");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Alamat");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        PeremCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        PeremCheckBox.setText("Perempuan");
        jPanel2.add(PeremCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        LakiCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        LakiCheckBox.setText("Laki - Laki");
        jPanel2.add(LakiCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        regbutton.setBackground(new java.awt.Color(51, 255, 51));
        regbutton.setForeground(new java.awt.Color(0, 0, 0));
        regbutton.setText("REGISTER");
        regbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(regbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 680));

        setSize(new java.awt.Dimension(1014, 682));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logMouseClicked
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logMouseClicked

    private void regbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbuttonActionPerformed
        // TODO add your handling code here:
        String nama = nama_kasir.getText();
        String alamat = alamatreg.getText();
        String umurText = umur.getText();
        String username = Usnreg.getText();
        String password = new String(Passreg.getPassword());
        String jenisKelamin = "";

        if (LakiCheckBox.isSelected()) {
            jenisKelamin = "Laki-laki";
        } else if (PeremCheckBox.isSelected()) {
            jenisKelamin = "Perempuan";
        }

        if (nama.isEmpty() || alamat.isEmpty() || umurText.isEmpty() || username.isEmpty() || password.isEmpty() || jenisKelamin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!");
            return;
        }

        try {
            int umur = Integer.parseInt(umurText);

            try (Connection conn = DatabaseConnection.koneksiDB();
                 PreparedStatement pstmt = conn.prepareStatement(
                         "INSERT INTO tabel_kasir (nama_kasir, alamat, jenis_kel, umur, username, password) VALUES (?, ?, ?, ?, ?, ?)")) {
                pstmt.setString(1, nama);
                pstmt.setString(2, alamat);
                pstmt.setString(3, jenisKelamin);
                pstmt.setInt(4, umur);
                pstmt.setString(5, username);
                pstmt.setString(6, password); // Tambahkan hashing jika diperlukan
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Registrasi Berhasil!");
                // Buka form login setelah registrasi berhasil
                new Login().setVisible(true);
                this.dispose();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Umur harus berupa angka!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error saat registrasi: " + ex.getMessage());
        }
    }//GEN-LAST:event_regbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox LakiCheckBox;
    private javax.swing.JPasswordField Passreg;
    private javax.swing.JCheckBox PeremCheckBox;
    private javax.swing.JTextField Usnreg;
    private javax.swing.JTextField alamatreg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel log;
    private javax.swing.JTextField nama_kasir;
    private javax.swing.JButton regbutton;
    private javax.swing.JTextField umur;
    // End of variables declaration//GEN-END:variables
}
